cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

# Paths to the basket
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *

# Name App
app_name = 'store'

# Paths to templates with app store views
urlpatterns = [
    path('', category_list, name='category-list'),
    path('catalog/<int:id>/', catalog_list, name='catalog-list'),
    path('product/<int:id>', product_list, name='product-list'),
    path('catalog/product/<int:pk>', product_detail, name='product-detail'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/models.py
from django.db import models


# Create Model Category main entity
# One to many relationship
class Category(models.Model):
    name = models.CharField(max_length=70, db_index=True)
    image = models.ImageField(default="catalog_pics/default.jpg", upload_to='catalog_pics/')
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    # Name display in table
    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = 'Категории'
        verbose_name_plural = 'Категория'


# Create Model Catalog
# One to many relationship
class Catalog(models.Model):
    title = models.CharField(max_length=150)
    image = models.ImageField(default="catalog_pics/default.jpg", upload_to='catalog_pics/')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='category')

    # Name display in table
    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']


# Create Model Product
class Product(models.Model):
    catalog = models.ForeignKey(Catalog, on_delete=models.PROTECT)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='products')
    name = models.CharField(max_length=100, db_index=True, verbose_name='Наименование')
    slug = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    description = models.TextField(blank=True, db_index=True, verbose_name='Описание')
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True, verbose_name='Наличие')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')
    updated = models.DateTimeField(auto_now=True, verbose_name='Изменен')
    image = models.ImageField(default="catalog_pics/default.jpg", upload_to='catalog_pics/')

    # Name display in table
    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

store/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse, request, HttpResponseNotFound
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.urls import reverse
from django.views.generic import ListView
from django.views.generic.detail import DetailView

from cart.forms import CartAddProductForm
from .models import Category, Catalog, Product


def category_list(request):
    category = Category.objects.all()
    context = {'category': category
    }
    return render(request, 'store/category_list.html', context=context)


def catalog_list(request, id):
    category = get_object_or_404(Category, id=id)
    catalog = Catalog.objects.filter(category_id=id)
    context = {'category': category, 'catalog': catalog
               }
    return render(request, 'store/catalog_list.html', context=context)

def product_list(request, id):
    catalog = get_object_or_404(Catalog, id=id)
    product = Product.objects.filter(catalog_id=id)
    context = {'catalog': catalog, 'product': product
               }
    return render(request, 'store/product_list.html', context=context)



# class ProductListView(ListView):
#     model = Product
#     template_name = 'product_list.html'
#     context_object_name = "product"


def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk, available=True)

    cart_product_form = CartAddProductForm()
    return render(request, 'store/product_detail.html', {'product': product,
                                                        'cart_product_form': cart_product_form})

store/templates/store/catalog_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section id='catalog' class="catalog">
        <div class="container">
          <div class="row">
            <div class="col-12">
              <h2 class="text-center text-uppercase mb-5">Каталог</h2>
            </div>
          </div>
            <div class="row">
                <div class="col-xl-4 col-md-6 col-sm-12">
                    {% for ct in catalog %}
                    {% if ct.image %}
                    <p><img src="{{ ct.image.url }}" width="'200" height="150" alt="Picture"></p>
                    <a href="{% url 'store:product-list' ct.id %}">
                        <button class="btn btn-primary" type="button">{{ct.title}}</button></a>
                    <div class="d-grid gap-2 d-md-block">
                    {% else %}
                        <img src="{% static 'catalog.pics/default.jpg' %}">
                    {% endif %}
                        </div>

                </div>
            </div>
        </div>
</section>
            {% endfor %}
            {% endblock content %}

store/templates/store/category_list.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
 <header>
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h1 class="text-center text-white">Магазин одежды</h1>
          <div class="itd_play" data-bs-toggle="modal" data-bs-target="#exampleModal">
            <div class="itd_triangle"></div>
          </div>
            <a href="#category" class="btn btn-itd btn-lg text-uppercase text-white">Магазин</a>
          </div>
        </div>
      </div>
  </header>
    <section id='category' class="category">
        <div class="container">
          <div class="row">
            <div class="col-12">
              <h2 class="text-center text-uppercase color2 mb-5">Категории</h2>
            </div>
          </div>
            <div class="row">
                <div class="col-xl-4 col-md-6 col-sm-12">
                    {% for ct in category %}
                    {% if ct.image %}
                    <p><img src="{{ ct.image.url }}" width="500" height="350" alt="Picture"></p>
                    {% else %}
                        <img src="{% static 'catalog.pics/default.jpg' %}">
                    {% endif %}
                    <div class="col-md-4">
                        <a href="{% url 'store:catalog-list' ct.id %}" class="btn btn-primary">{{ct.name}}</a>
                    </div>
                     {% endfor %}
                </div>
            </div>

        </section>
{% endblock content %}

store/templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>{{ product.name }}</h1>

{% if product.image %}
        <img src="{{ product.image.url }}" width="'200" height="150" alt="Picture">
{% else %}
    <img src="{% static 'catalog.pics/default.jpg' %}">
{% endif %}

    <span class='lead'>Цена: {{ product.price }} $</span>
        <p>Категория:{{ product.category }}</p>
        <p>Описание:{{ product.description }}</p>
        <p>Остаток на складе:{{ product.stock }}</p>
        <p>{{ product.updated }}</p>
        <p class="price">${{ product.price }}</p>
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ cart_product_form }}
                {% csrf_token %}
        <input type="submit" value="Добавить в корзину">
            </form>




{% endblock content %}

store/templates/store/product_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link href="/static/bootstrap/css/bootstrap.css" type="text/css" rel="stylesheet">
{%  for pr in product %}
{% if pr.image %}
        <img src="{{ pr.image.url }}" width="'200" height="150" alt="Picture">
{% else %}
    <img src="{% static 'catalog.pics/default.jpg' %}">
{% endif %}
            <div class="col-md-4">
                <p>{{pr.name}}</p>
                <p>Цена: {{ pr.price }} $ </p>
                <p>Описание: {{ pr.description }}</p>
                <a href="{% url 'store:product-detail' pr.pk %}" class="btn btn-primary">Хочу купить!</a>
             </div>

{% endfor %}


{% endblock content %}