cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

# Paths to the basket
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *

# Name App
app_name = 'store'

# Paths to templates with app store views
urlpatterns = [
    path('', category_list, name='category-list'),
    path('catalog/<int:id>/', catalog_list, name='catalog-list'),
    path('product/<int:id>', product_list, name='product-list'),
    path('catalog/product/<int:pk>', product_detail, name='product-detail'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% block head %}

<head>
      <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>SHOP</title>
    {% load static %}
  <link rel="stylesheet" href="{% static 'my_site/css/bootstrap.min.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'my_site/css/fontello.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'my_site/css/style.css' %}" type="text/css">
    <script src="{% static 'my_site/js/bootstrap.bundle.min.js' %}"></script>
</head>

<html>
<style>

body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.topnav {
  overflow: hidden;
  background-color: #333;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.topnav a.active {
  background-color: #4CAF50;
  color: white;
}
</style>

<head>
<meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
        <div class="topnav">
          <a class='nav-item nav-link' href="{% url 'store:category-list' %}">Главная</a>
          <a href="#">Избранное</a>
          {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'profile' %}">Личный кабинет</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Выход</a>
            {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Вход</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Регистрация</a>
            {% endif %}
        <div id="subheader">

              <div class="cart">
                  {% with total_items=cart|length %}
                  {% if cart|length > 0 %}
                   В корзине:
                  <a href="{% url 'cart:cart_detail' %}">
                      {{ total_items }} шт, ${{ cart.get_total_price }}
                  </a>
                  {% else %}
                  <a href="#">Корзина пустая</a>
                  {% endif %}
                  {% endwith %}
              </div>
          </div>
        </div>


</body>
</html>
{% endblock %}

{% block content %}
{% endblock %}

{% block footer %}
<h7>Контактный телефон: +375 66 374 43 99</h7>
{% endblock %}